### ISSUE TITLE
Specific reference to TAG in external project fails 

### ISSUE THREAD

**Issue by ghost** [marcusabate/dbow2_catkin#2]
Build failed due to failing to find tag: origin/master.
This was fixed when I removed:
```
  GIT_TAG master
  GIT_PROGRESS 1
  UPDATE_COMMAND ""
  #PATCH_COMMAND ""
```

**Comment by vik748** [comment]
FYI, in Ubuntu 16.04 I had to comment out `GIT_PROGRESS 1` while leaving the tag as origin/master to make this work.  Might have to do with the version of cmake.
